/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceAdmin;

import globals.Globals;
import java.awt.Color;
import javax.swing.JOptionPane;
import progra2objetos.RoomType;

/**
 *
 * @author kevin
 */
public class NewRoomType extends javax.swing.JFrame {
        Globals newGlobals = Globals.getInstance();
        RoomType newRoomType;
        boolean allInclusive;
        boolean terrace;
        boolean seaview;
        boolean smoke;
        boolean livingRoom;
    /**
     * Creates new form NewRoomType
     */
    public NewRoomType() {
        initComponents();
        this.getContentPane().setBackground(Color.DARK_GRAY);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Add New Room Type");
    }
    
     public void AddNewTypeRoom(){
         String Bedding = jTextFieldBedding.getText();
         
         String roomType = jTextFieldRoomType.getText();
         String description = jTextAreaDescription.getText();
         int price;
         int roomSize;
         int maxPersons;
        
         try {
              price = Integer.parseInt(jTextFieldPrice.getText());
              roomSize = Integer.parseInt(jTextFieldRoomSize.getText());
              maxPersons = Integer.parseInt(jTextFieldMaxPersons.getText());
             
         } catch (Exception e) {
             System.out.println("Price,room size and max persons are only for integer values");
             return;
         }
         
         RoomType newRoomType = new RoomType(Bedding, maxPersons, roomType, description, livingRoom, terrace, seaview, allInclusive, smoke, roomSize, price);
         newGlobals.setNewRoomType(newRoomType);
         
          
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRoomType = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldBedding = new javax.swing.JTextField();
        jTextFieldRoomSize = new javax.swing.JTextField();
        jTextFieldMaxPersons = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jRadioButtonAllinclusive = new javax.swing.JRadioButton();
        jRadioButtonlivingRoom = new javax.swing.JRadioButton();
        jRadioButtonSeaView = new javax.swing.JRadioButton();
        jRadioButtonTerrace = new javax.swing.JRadioButton();
        jRadioButtonSmoke = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Room Type");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Description");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Maximun Persons");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Room Size");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bedding");

        jButton1.setText("back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");

        jButtonSave.setText("Save");
        jButtonSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jRadioButtonAllinclusive.setBackground(java.awt.Color.darkGray);
        jRadioButtonAllinclusive.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAllinclusive.setText("Everything included");
        jRadioButtonAllinclusive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAllinclusiveActionPerformed(evt);
            }
        });

        jRadioButtonlivingRoom.setBackground(java.awt.Color.darkGray);
        jRadioButtonlivingRoom.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonlivingRoom.setText("Living Room");
        jRadioButtonlivingRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonlivingRoomActionPerformed(evt);
            }
        });

        jRadioButtonSeaView.setBackground(java.awt.Color.darkGray);
        jRadioButtonSeaView.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeaView.setText("Seaview");
        jRadioButtonSeaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSeaViewActionPerformed(evt);
            }
        });

        jRadioButtonTerrace.setBackground(java.awt.Color.darkGray);
        jRadioButtonTerrace.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonTerrace.setText("Terrace");
        jRadioButtonTerrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTerraceActionPerformed(evt);
            }
        });

        jRadioButtonSmoke.setBackground(java.awt.Color.darkGray);
        jRadioButtonSmoke.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSmoke.setText("Smoke");
        jRadioButtonSmoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSmokeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonAllinclusive)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonlivingRoom)
                                    .addComponent(jRadioButtonSeaView))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonTerrace)
                                    .addComponent(jRadioButtonSmoke)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldBedding, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMaxPersons)
                                    .addComponent(jTextFieldRoomSize))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldBedding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldRoomSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMaxPersons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonAllinclusive)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonlivingRoom)
                    .addComponent(jRadioButtonTerrace))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonSeaView)
                        .addComponent(jRadioButtonSmoke))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InterfaceAdmin newWindows = new InterfaceAdmin();
        this.dispose();
        newWindows.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        AddNewTypeRoom();
        JOptionPane.showMessageDialog(this,"New Type Room is Added");
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jRadioButtonAllinclusiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAllinclusiveActionPerformed
        if(jRadioButtonAllinclusive.isSelected()){  
             allInclusive = true;
             terrace = true;
             seaview = true;
             livingRoom = true;
             smoke = true;
             
             jRadioButtonSeaView.setEnabled(false);
             jRadioButtonSmoke.setEnabled(false);
             jRadioButtonTerrace.setEnabled(false);
             jRadioButtonlivingRoom.setEnabled(false);
             
         }
        else{  
             jRadioButtonSeaView.setEnabled(true);
             jRadioButtonSmoke.setEnabled(true);
             jRadioButtonTerrace.setEnabled(true);
             jRadioButtonlivingRoom.setEnabled(true); 
             allInclusive = false;
             terrace = false;
             seaview = false;
             livingRoom = false;
             smoke = false;
             
         }
    }//GEN-LAST:event_jRadioButtonAllinclusiveActionPerformed

    private void jRadioButtonlivingRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonlivingRoomActionPerformed
        if ((jRadioButtonlivingRoom.isSelected())&&(!jRadioButtonAllinclusive.isSelected())) {
            livingRoom = true;
        }else{
            livingRoom = false;
        }
    }//GEN-LAST:event_jRadioButtonlivingRoomActionPerformed

    private void jRadioButtonTerraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTerraceActionPerformed
        if ((jRadioButtonTerrace.isSelected())&&(!jRadioButtonAllinclusive.isSelected())) {
            terrace = true;
        }else{
            terrace = false;
        }
    }//GEN-LAST:event_jRadioButtonTerraceActionPerformed

    private void jRadioButtonSeaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSeaViewActionPerformed
        if ((jRadioButtonSeaView.isSelected())&&(!jRadioButtonAllinclusive.isSelected())) {
            seaview = true;
        }else{
            seaview = false;
        }
    }//GEN-LAST:event_jRadioButtonSeaViewActionPerformed

    private void jRadioButtonSmokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSmokeActionPerformed
        if ((jRadioButtonSmoke.isSelected())&&(!jRadioButtonAllinclusive.isSelected())) {
            smoke = true;
        }else{
            smoke = false;
        }
    }//GEN-LAST:event_jRadioButtonSmokeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewRoomType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewRoomType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewRoomType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewRoomType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewRoomType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButtonAllinclusive;
    private javax.swing.JRadioButton jRadioButtonSeaView;
    private javax.swing.JRadioButton jRadioButtonSmoke;
    private javax.swing.JRadioButton jRadioButtonTerrace;
    private javax.swing.JRadioButton jRadioButtonlivingRoom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldBedding;
    private javax.swing.JTextField jTextFieldMaxPersons;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldRoomSize;
    private javax.swing.JTextField jTextFieldRoomType;
    // End of variables declaration//GEN-END:variables
}
